### ISSUE TITLE
React Hooks에 대한 Eslint 고려하기

### ISSUE THREAD

**Issue by pdvonzoo** [ozohn/H-SENS#26]
React Hooks에 대한 Eslint 고려하기

**Comment by crongro** [comment]
linting은 hooks 아니더라도 이제 제대로 해보는 게 좋아요.

**Comment by HTMLhead** [comment]
commit id : [abb5f65](https://github.com/ozohn/H-SENS/commit/abb5f655c036f19a03c3c9cf06a94a642f00fe8c)
