### ISSUE TITLE
메인 페이지

### ISSUE THREAD

**Issue by pdvonzoo** [ozohn/H-SENS#55]
* [ ] 메인 페이지에서 작가 선택했을때 creator 페이지 렌더링 (라우터)
* [ ] 선택한 작가의 정보들이 페이지에 렌더링된다.

**Comment by HTMLhead** [comment]
본 이슈는 수정되는 사항이 있기 때문에 새로운 이슈를 생성하여 재 정의 하였습니다.
#69
